debug = true

# Suzu の HTTP リクエストの待ち受けアドレスとポートです
listen_addr = "127.0.0.1"
listen_port = 48080

exporter_ip_address = "127.0.0.1"
exporter_port = 48081

skip_basic_auth = true

# 音声データのサンプリングレートです
audio_sample_rate = 48000
# 音声データのチャネル数です
audio_channel_count = 1

# 受信した音声データの保存先ファイルです
dump_file = "./dump.jsonl"

# [http2]
# Suzu のサーバ証明書ファイルです
http2_fullchain_file = ""
# Suzu の秘密鍵ファイルです
http2_privkey_file = ""
# クライアント認証用の CA 証明書ファイルです
http2_verify_cacert_path = ""

# サーバからの切断時に再接続を試みます
retry = true

# aws の場合は IsPartial が false, gcp の場合は IsFinal が true の場合の最終的な結果のみを返す指定
final_result_only = true

# [log]
# ログの出力先ディレクトリです
log_dir = "."
# ログの出力先ファイルのファイル名です
log_name = "suzu.jsonl"
log_debug = false
# ログを標準出力に出力可否の指定です
# true にした場合はファイルにログは出力されません
log_stdout = true

# [aws]
aws_region = "ap-northeast-1"
# Partial-result stabilization の有効化です
aws_enable_partial_results_stabilization = false
# 安定化レベルの指定です（high, medium, low）
# aws_partial_results_stability = "low"
# マルチチャネルの音声のチャネル識別の有効化です
aws_enable_channel_identification = false
# 認証情報ファイルの指定です
aws_credential_file = "./credentials"
# プロファイルの指定です
# 認証情報に AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY を使用する場合は、下記のプロファイルの指定行をコメントアウトします
aws_profile = "default"

# クライアントに送る変換結果の情報に付与する項目
aws_result_channel_id = true
# aws_result_is_partial = true


# https://cloud.google.com/speech-to-text/docs/reference/rpc/google.cloud.speech.v1#streamingrecognitionconfig
# https://cloud.google.com/speech-to-text/docs/reference/rpc/google.cloud.speech.v1#recognitionconfig
# [gcp]
# 1 つだけの発話を検出するかの設定です。ture にした場合は 1 つの発話を検出すると、それ以降の発話をテキスト化した結果は返ってきません
gcp_single_utterance = false
# テキスト化の中間結果を返すかの設定です
gcp_interim_results = true
# GCP の認証情報ファイル（JSON）の指定です。GOOGLE_APPLICATION_CREDENTIALS で認証情報ファイルを指定する場合は下記のファイルの指定行をコメントアウトします
gcp_credential_file = ""
# gcp_enable_separate_recognition_per_channel = false
# gcp_alternative_language_codes = []
# gcp_max_alternatives = 1
# gcp_profanity_filter = false
# gcp_enable_word_time_offsets = false
# gcp_enable_word_confidence = false
# gcp_enable_automatic_punctuation = false
# gcp_enable_spoken_punctuation = false
# gcp_model = "default"
# gcp_use_enhanced = false
# クライアントに送る変換結果の情報に付与する項目
# gcp_result_is_final = true
# gcp_result_stability = true